#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
  path:       /{_locale}/
  controller: App\Controller\HomepageController::index
  requirements:
    _locale: cs|en|de
